language: python
sudo: true

before_install:
  - sudo wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
  - sudo dpkg -i pandoc-2.7.3-1-amd64.deb
  - pandoc --version

install:
    - pip install tox
    - pip install coveralls

script:
    - tox -r


matrix:
  include:

      - env: TOXENV=docstyle
        python: 3.8
        sudo: true

      - env: TOXENV=check-manifest
        python: 3.8
        sudo: true

      - env: TOXENV=makedocs
        python: 3.8
        sudo: true

      - env: TOXENV=style
        python: 3.8
        sudo: true

      - env: TOXENV=coverage
        python: 3.8
        sudo: true

      - env: TOXENV=py38
        python: 3.8
        sudo: true

after_success:
  - coveralls